/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.petcare.view.petOwnerFrames;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import com.petcare.controller.PetOwnerController;
import com.petcare.exception.DatabaseConfigException;
import com.petcare.model.Pet;
import com.petcare.model.User;
import com.petcare.util.ErrorHandler;
import com.petcare.view.UiStyle;

/**
 *
 * @author hirunaka
 */
public class MyPetsPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    private PetOwnerController controller;
    private User user;
    private List<Pet> pets;

    // Created before initComponents() because the form's table uses it as its model
    private final DefaultTableModel tableModel = new DefaultTableModel(
            new String[] {"Name", "Species", "Gender", "Actions"}, 0) {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form MyPetsPanel
     */
    public MyPetsPanel(User user) {
        controller = new PetOwnerController();
        this.user = user;

        initComponents();

        UiStyle.styleTable(petsTable);
        UiStyle.styleScrollPane(scrollPane);
        initTableBehaviour();

        loadPets();
    }

    /**
     * "Edit" link column: renderer, click and hover cursor.
     */
    private void initTableBehaviour() {
        DefaultTableCellRenderer editRenderer = new DefaultTableCellRenderer() {
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                label.setText("<html><u>Edit</u></html>");
                label.setHorizontalAlignment(JLabel.CENTER);
                if (!isSelected) {
                    label.setForeground(UiStyle.ACCENT);
                }

                return label;
            }
        };

        petsTable.getColumnModel().getColumn(3).setCellRenderer(editRenderer);

        petsTable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {

                int row = petsTable.rowAtPoint(e.getPoint());
                int column = petsTable.columnAtPoint(e.getPoint());

                if (column == 3 && row >= 0 && pets != null && row < pets.size()) {

                    Pet pet = pets.get(row);

                    EditPetDialog dialog = new EditPetDialog(user, pet);
                    dialog.setVisible(true);

                    if (dialog.isChanged()) {
                        loadPets();
                    }
                }
            }
        });

        petsTable.addMouseMotionListener(new MouseAdapter() {
            public void mouseMoved(MouseEvent e) {

                int row = petsTable.rowAtPoint(e.getPoint());
                int column = petsTable.columnAtPoint(e.getPoint());

                if (column == 3 && row >= 0 && pets != null && row < pets.size()) {
                    petsTable.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                } else {
                    petsTable.setCursor(Cursor.getDefaultCursor());
                }
            }
        });
    }

    private void loadPets() {
        tableModel.setRowCount(0);

        try {
            pets = controller.getOwnerPets(user);

            for (Pet pet : pets) {
                tableModel.addRow(new Object[] {
                        pet.getName(),
                        pet.getSpecies(),
                        pet.getGender(),
                        "Edit"
                });
            }
        } catch (SQLException e) {
            ErrorHandler.handleTableLoadError(e, petsTable, tableModel);
        } catch (DatabaseConfigException e) {
            ErrorHandler.handleTableLoadError(e, petsTable, tableModel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        btnAddPet = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        petsTable = new javax.swing.JTable();

        setOpaque(false);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(33, 37, 41));
        lblTitle.setText("My Pets");

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(108, 117, 125));
        lblSubtitle.setText("Manage your registered pets");

        btnAddPet.setBackground(new java.awt.Color(0, 121, 107));
        btnAddPet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddPet.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPet.setText("+ Add Pet");
        btnAddPet.setBorderPainted(false);
        btnAddPet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddPet.setFocusPainted(false);
        btnAddPet.addActionListener(this::btnAddPetActionPerformed);

        petsTable.setModel(tableModel);
        scrollPane.setViewportView(petsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblSubtitle))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddPet, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(4, 4, 4)
                        .addComponent(lblSubtitle))
                    .addComponent(btnAddPet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPetActionPerformed
        AddPetDialog dialog = new AddPetDialog(user);
        dialog.setVisible(true);

        if (dialog.isChanged()) {
            loadPets();
        }
    }//GEN-LAST:event_btnAddPetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPet;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable petsTable;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
