/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.petcare.view.vetFrames;

import java.awt.Color;
import java.time.format.DateTimeFormatter;

import com.petcare.model.Pet;

/**
 *
 * @author hirunaka
 */
public class ViewPatientDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form ViewPatientDialog
     */
    public ViewPatientDialog(Pet pet) {
        initComponents();

        getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(null);

        // Fill in the patient details; a missing value is shown as N/A
        lblPetValue.setText(valueOrNA(pet.getName()));
        lblSpeciesValue.setText(valueOrNA(pet.getSpecies()));
        lblOwnerValue.setText(valueOrNA(pet.getOwnerName()));
        lblLastApptValue.setText(pet.getLastAppointment() == null ? "N/A"
                : pet.getLastAppointment().toLocalDateTime().format(DateTimeFormatter.ofPattern("dd MMM yyyy, h:mm a")));
    }

    private String valueOrNA(String value) {
        return value == null ? "N/A" : value;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPetKey = new javax.swing.JLabel();
        lblPetValue = new javax.swing.JLabel();
        lblSpeciesKey = new javax.swing.JLabel();
        lblSpeciesValue = new javax.swing.JLabel();
        lblOwnerKey = new javax.swing.JLabel();
        lblOwnerValue = new javax.swing.JLabel();
        lblLastApptKey = new javax.swing.JLabel();
        lblLastApptValue = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setTitle("Patient Details");
        setModal(true);
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(33, 37, 41));
        lblTitle.setText("Patient Details");

        lblPetKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPetKey.setForeground(new java.awt.Color(108, 117, 125));
        lblPetKey.setText("Pet");

        lblPetValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPetValue.setForeground(new java.awt.Color(33, 37, 41));
        lblPetValue.setText("Pet name");

        lblSpeciesKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSpeciesKey.setForeground(new java.awt.Color(108, 117, 125));
        lblSpeciesKey.setText("Species");

        lblSpeciesValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSpeciesValue.setForeground(new java.awt.Color(33, 37, 41));
        lblSpeciesValue.setText("Species");

        lblOwnerKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblOwnerKey.setForeground(new java.awt.Color(108, 117, 125));
        lblOwnerKey.setText("Owner");

        lblOwnerValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOwnerValue.setForeground(new java.awt.Color(33, 37, 41));
        lblOwnerValue.setText("Owner name");

        lblLastApptKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLastApptKey.setForeground(new java.awt.Color(108, 117, 125));
        lblLastApptKey.setText("Last Appointment");

        lblLastApptValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLastApptValue.setForeground(new java.awt.Color(33, 37, 41));
        lblLastApptValue.setText("Date and time");

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(33, 37, 41));
        btnClose.setText("Close");
        btnClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)));
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusPainted(false);
        btnClose.addActionListener(this::btnCloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPetKey, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSpeciesKey)
                            .addComponent(lblOwnerKey)
                            .addComponent(lblLastApptKey))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPetValue, 0, 254, Short.MAX_VALUE)
                            .addComponent(lblSpeciesValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOwnerValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLastApptValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPetKey)
                    .addComponent(lblPetValue))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpeciesKey)
                    .addComponent(lblSpeciesValue))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOwnerKey)
                    .addComponent(lblOwnerValue))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastApptKey)
                    .addComponent(lblLastApptValue))
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblLastApptKey;
    private javax.swing.JLabel lblLastApptValue;
    private javax.swing.JLabel lblOwnerKey;
    private javax.swing.JLabel lblOwnerValue;
    private javax.swing.JLabel lblPetKey;
    private javax.swing.JLabel lblPetValue;
    private javax.swing.JLabel lblSpeciesKey;
    private javax.swing.JLabel lblSpeciesValue;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
