/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.petcare.view.vetFrames;

import java.awt.Color;
import java.time.format.DateTimeFormatter;

import com.petcare.model.Treatment;
import com.petcare.model.User;

/**
 *
 * @author hirunaka
 */
public class ViewTreatmentDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    private User user;
    private Treatment treatment;
    private boolean changed = false;

    /**
     * Creates new form ViewTreatmentDialog
     */
    public ViewTreatmentDialog(User user, Treatment treatment) {
        this.user = user;
        this.treatment = treatment;

        initComponents();

        getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(null);

        // Fill in the treatment details; a missing value is shown as N/A
        lblPetValue.setText(valueOrNA(treatment.getPetName()));
        lblOwnerValue.setText(valueOrNA(treatment.getOwnerName()));
        lblVetValue.setText(valueOrNA(treatment.getVetName()));
        lblDateValue.setText(treatment.getTreatmentDate() == null ? "N/A"
                : treatment.getTreatmentDate().toLocalDateTime().format(DateTimeFormatter.ofPattern("dd MMM yyyy, h:mm a")));
        lblStatusValue.setText(valueOrNA(treatment.getStatus()));
        setText(txtDiagnosis, treatment.getDiagnosis());
        setText(txtTreatment, treatment.getTreatmentDescription());
        setText(txtMedication, treatment.getMedication());
    }

    private String valueOrNA(String value) {
        return value == null ? "N/A" : value;
    }

    /**
     * Fills a read-only text area; a missing value is shown as N/A.
     */
    private void setText(javax.swing.JTextArea area, String value) {
        area.setText(valueOrNA(value));
        area.setCaretPosition(0);
    }

    public boolean isChanged() {
        return changed;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPetKey = new javax.swing.JLabel();
        lblPetValue = new javax.swing.JLabel();
        lblOwnerKey = new javax.swing.JLabel();
        lblOwnerValue = new javax.swing.JLabel();
        lblVetKey = new javax.swing.JLabel();
        lblVetValue = new javax.swing.JLabel();
        lblDateKey = new javax.swing.JLabel();
        lblDateValue = new javax.swing.JLabel();
        lblStatusKey = new javax.swing.JLabel();
        lblStatusValue = new javax.swing.JLabel();
        lblDiagnosisKey = new javax.swing.JLabel();
        diagnosisScrollPane = new javax.swing.JScrollPane();
        txtDiagnosis = new javax.swing.JTextArea();
        lblTreatmentKey = new javax.swing.JLabel();
        treatmentScrollPane = new javax.swing.JScrollPane();
        txtTreatment = new javax.swing.JTextArea();
        lblMedicationKey = new javax.swing.JLabel();
        medicationScrollPane = new javax.swing.JScrollPane();
        txtMedication = new javax.swing.JTextArea();
        btnEdit = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setTitle("Treatment Details");
        setModal(true);
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(33, 37, 41));
        lblTitle.setText("Treatment Details");

        lblPetKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPetKey.setForeground(new java.awt.Color(108, 117, 125));
        lblPetKey.setText("Pet");

        lblPetValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPetValue.setForeground(new java.awt.Color(33, 37, 41));
        lblPetValue.setText("Pet name");

        lblOwnerKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblOwnerKey.setForeground(new java.awt.Color(108, 117, 125));
        lblOwnerKey.setText("Owner");

        lblOwnerValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOwnerValue.setForeground(new java.awt.Color(33, 37, 41));
        lblOwnerValue.setText("Owner name");

        lblVetKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblVetKey.setForeground(new java.awt.Color(108, 117, 125));
        lblVetKey.setText("Veterinarian");

        lblVetValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVetValue.setForeground(new java.awt.Color(33, 37, 41));
        lblVetValue.setText("Vet name");

        lblDateKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDateKey.setForeground(new java.awt.Color(108, 117, 125));
        lblDateKey.setText("Date");

        lblDateValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDateValue.setForeground(new java.awt.Color(33, 37, 41));
        lblDateValue.setText("Date and time");

        lblStatusKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblStatusKey.setForeground(new java.awt.Color(108, 117, 125));
        lblStatusKey.setText("Status");

        lblStatusValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatusValue.setForeground(new java.awt.Color(33, 37, 41));
        lblStatusValue.setText("Status");

        lblDiagnosisKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDiagnosisKey.setForeground(new java.awt.Color(108, 117, 125));
        lblDiagnosisKey.setText("Diagnosis");

        diagnosisScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)));

        txtDiagnosis.setEditable(false);
        txtDiagnosis.setColumns(20);
        txtDiagnosis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiagnosis.setForeground(new java.awt.Color(33, 37, 41));
        txtDiagnosis.setLineWrap(true);
        txtDiagnosis.setRows(3);
        txtDiagnosis.setWrapStyleWord(true);
        txtDiagnosis.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10));
        diagnosisScrollPane.setViewportView(txtDiagnosis);

        lblTreatmentKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTreatmentKey.setForeground(new java.awt.Color(108, 117, 125));
        lblTreatmentKey.setText("Treatment");

        treatmentScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)));

        txtTreatment.setEditable(false);
        txtTreatment.setColumns(20);
        txtTreatment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTreatment.setForeground(new java.awt.Color(33, 37, 41));
        txtTreatment.setLineWrap(true);
        txtTreatment.setRows(3);
        txtTreatment.setWrapStyleWord(true);
        txtTreatment.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10));
        treatmentScrollPane.setViewportView(txtTreatment);

        lblMedicationKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMedicationKey.setForeground(new java.awt.Color(108, 117, 125));
        lblMedicationKey.setText("Medication");

        medicationScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)));

        txtMedication.setEditable(false);
        txtMedication.setColumns(20);
        txtMedication.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMedication.setForeground(new java.awt.Color(33, 37, 41));
        txtMedication.setLineWrap(true);
        txtMedication.setRows(3);
        txtMedication.setWrapStyleWord(true);
        txtMedication.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10));
        medicationScrollPane.setViewportView(txtMedication);

        btnEdit.setBackground(new java.awt.Color(0, 121, 107));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit Treatment");
        btnEdit.setBorderPainted(false);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setFocusPainted(false);
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(33, 37, 41));
        btnClose.setText("Close");
        btnClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)));
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusPainted(false);
        btnClose.addActionListener(this::btnCloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPetKey, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOwnerKey)
                            .addComponent(lblVetKey)
                            .addComponent(lblDateKey)
                            .addComponent(lblStatusKey)
                            .addComponent(lblDiagnosisKey)
                            .addComponent(lblTreatmentKey)
                            .addComponent(lblMedicationKey))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPetValue, 0, 264, Short.MAX_VALUE)
                            .addComponent(lblOwnerValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVetValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDateValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatusValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diagnosisScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(treatmentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medicationScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPetKey)
                    .addComponent(lblPetValue))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOwnerKey)
                    .addComponent(lblOwnerValue))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVetKey)
                    .addComponent(lblVetValue))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateKey)
                    .addComponent(lblDateValue))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusKey)
                    .addComponent(lblStatusValue))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiagnosisKey)
                    .addComponent(diagnosisScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTreatmentKey)
                    .addComponent(treatmentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicationKey)
                    .addComponent(medicationScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        EditTreatmentDialog dialog = new EditTreatmentDialog(user, treatment);
        dialog.setVisible(true);

        if (dialog.isChanged()) {
            changed = true;
            dispose();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane diagnosisScrollPane;
    private javax.swing.JLabel lblDateKey;
    private javax.swing.JLabel lblDateValue;
    private javax.swing.JLabel lblDiagnosisKey;
    private javax.swing.JLabel lblMedicationKey;
    private javax.swing.JLabel lblOwnerKey;
    private javax.swing.JLabel lblOwnerValue;
    private javax.swing.JLabel lblPetKey;
    private javax.swing.JLabel lblPetValue;
    private javax.swing.JLabel lblStatusKey;
    private javax.swing.JLabel lblStatusValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTreatmentKey;
    private javax.swing.JLabel lblVetKey;
    private javax.swing.JLabel lblVetValue;
    private javax.swing.JScrollPane medicationScrollPane;
    private javax.swing.JScrollPane treatmentScrollPane;
    private javax.swing.JTextArea txtDiagnosis;
    private javax.swing.JTextArea txtMedication;
    private javax.swing.JTextArea txtTreatment;
    // End of variables declaration//GEN-END:variables
}
