/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.petcare.view;

import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import com.petcare.controller.RegisterController;
import com.petcare.controller.RegisterFieldEnum;
import com.petcare.exception.DatabaseConfigException;
import com.petcare.util.ErrorHandler;

/**
 *
 * @author hirunaka
 */
public class RegisterFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterFrame.class.getName());

    private static final java.awt.Color ACCENT = new java.awt.Color(0, 121, 107);
    private static final java.awt.Color ACCENT_DISABLED = new java.awt.Color(176, 190, 197);
    private static final String NO_ERROR = " ";

    private RegisterController controller;

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        controller = new RegisterController();
        initComponents();
        setLocationRelativeTo(null);
        initFieldListeners();
        updateSubmitButton();
    }

    /**
     * Enables the submit button only when every field is filled.
     */
    private void updateSubmitButton() {
        boolean filled = !txtFName.getText().trim().isEmpty()
                && !txtLName.getText().trim().isEmpty()
                && !txtEmail.getText().trim().isEmpty()
                && !txtPhone.getText().trim().isEmpty()
                && !txtUsername.getText().trim().isEmpty()
                && pwField.getPassword().length > 0
                && confirmPwField.getPassword().length > 0;

        btnSubmit.setEnabled(filled);
        btnSubmit.setBackground(filled ? ACCENT : ACCENT_DISABLED);
    }

    private void initFieldListeners() {
        DocumentListener listener = new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                updateSubmitButton();
            }

            public void removeUpdate(DocumentEvent e) {
                updateSubmitButton();
            }

            public void changedUpdate(DocumentEvent e) {
                updateSubmitButton();
            }
        };
        txtFName.getDocument().addDocumentListener(listener);
        txtLName.getDocument().addDocumentListener(listener);
        txtEmail.getDocument().addDocumentListener(listener);
        txtPhone.getDocument().addDocumentListener(listener);
        txtUsername.getDocument().addDocumentListener(listener);
        pwField.getDocument().addDocumentListener(listener);
        confirmPwField.getDocument().addDocumentListener(listener);
    }

    private void clearErrors() {
        fNameError.setText(NO_ERROR);
        lNameError.setText(NO_ERROR);
        emailError.setText(NO_ERROR);
        phoneError.setText(NO_ERROR);
        usernameError.setText(NO_ERROR);
        pwError.setText(NO_ERROR);
        confirmPwError.setText(NO_ERROR);
    }

    // Helper method
    private boolean showValidationError(RegisterFieldEnum field, String value, JLabel errorLabel) {
        String error = controller.validateField(field, value);

        if (error != null) {
            errorLabel.setText(error);
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        fNameError = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        lNameError = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        emailError = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPhonePrefix = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        phoneError = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        usernameError = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        pwField = new javax.swing.JPasswordField();
        pwError = new javax.swing.JLabel();
        lblConfirmPw = new javax.swing.JLabel();
        confirmPwField = new javax.swing.JPasswordField();
        confirmPwError = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblBackToLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetCare - Register");
        setResizable(false);

        headerPanel.setBackground(new java.awt.Color(0, 121, 107));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Account");

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(224, 242, 241));
        lblSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitle.setText("Join PetCareSys in a few quick steps");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(4, 4, 4)
                .addComponent(lblSubtitle)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(73, 80, 87));
        lblFirstName.setText("First Name");

        txtFName.setBackground(new java.awt.Color(204, 204, 204));
        txtFName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFName.setForeground(new java.awt.Color(33, 37, 41));
        txtFName.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10)));
        txtFName.setCaretColor(new java.awt.Color(51, 51, 51));

        fNameError.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        fNameError.setForeground(new java.awt.Color(220, 53, 69));
        fNameError.setText(" ");

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(73, 80, 87));
        lblLastName.setText("Last Name");

        txtLName.setBackground(new java.awt.Color(204, 204, 204));
        txtLName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLName.setForeground(new java.awt.Color(33, 37, 41));
        txtLName.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10)));
        txtLName.setCaretColor(new java.awt.Color(51, 51, 51));

        lNameError.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lNameError.setForeground(new java.awt.Color(220, 53, 69));
        lNameError.setText(" ");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(73, 80, 87));
        lblEmail.setText("Email");

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(33, 37, 41));
        txtEmail.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10)));
        txtEmail.setCaretColor(new java.awt.Color(51, 51, 51));

        emailError.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        emailError.setForeground(new java.awt.Color(220, 53, 69));
        emailError.setText(" ");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(73, 80, 87));
        lblPhone.setText("Phone no.");

        lblPhonePrefix.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhonePrefix.setForeground(new java.awt.Color(73, 80, 87));
        lblPhonePrefix.setText("+94");

        txtPhone.setBackground(new java.awt.Color(204, 204, 204));
        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(33, 37, 41));
        txtPhone.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10)));
        txtPhone.setCaretColor(new java.awt.Color(51, 51, 51));

        phoneError.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        phoneError.setForeground(new java.awt.Color(220, 53, 69));
        phoneError.setText(" ");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(73, 80, 87));
        lblUsername.setText("Username");

        txtUsername.setBackground(new java.awt.Color(204, 204, 204));
        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(33, 37, 41));
        txtUsername.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10)));
        txtUsername.setCaretColor(new java.awt.Color(51, 51, 51));

        usernameError.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        usernameError.setForeground(new java.awt.Color(220, 53, 69));
        usernameError.setText(" ");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(73, 80, 87));
        lblPassword.setText("Password");

        pwField.setBackground(new java.awt.Color(204, 204, 204));
        pwField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pwField.setForeground(new java.awt.Color(33, 37, 41));
        pwField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10)));
        pwField.setCaretColor(new java.awt.Color(51, 51, 51));

        pwError.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pwError.setForeground(new java.awt.Color(220, 53, 69));
        pwError.setText(" ");

        lblConfirmPw.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblConfirmPw.setForeground(new java.awt.Color(73, 80, 87));
        lblConfirmPw.setText("Confirm Password");

        confirmPwField.setBackground(new java.awt.Color(204, 204, 204));
        confirmPwField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmPwField.setForeground(new java.awt.Color(33, 37, 41));
        confirmPwField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10)));
        confirmPwField.setCaretColor(new java.awt.Color(51, 51, 51));
        confirmPwField.addActionListener(this::confirmPwFieldActionPerformed);

        confirmPwError.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        confirmPwError.setForeground(new java.awt.Color(220, 53, 69));
        confirmPwError.setText(" ");

        btnSubmit.setBackground(new java.awt.Color(0, 121, 107));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setBorderPainted(false);
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.setEnabled(false);
        btnSubmit.setFocusPainted(false);
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        lblBackToLogin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblBackToLogin.setForeground(new java.awt.Color(0, 121, 107));
        lblBackToLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackToLogin.setText("Back to Login");
        lblBackToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBackToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackToLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackToLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackToLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNameError, 0, 206, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyPanelLayout.createSequentialGroup()
                                .addComponent(lblLastName)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lNameError, 0, 207, Short.MAX_VALUE)
                            .addComponent(txtLName)))
                    .addComponent(lblEmail)
                    .addComponent(txtEmail)
                    .addComponent(emailError, 0, 0, Short.MAX_VALUE)
                    .addComponent(lblPhone)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(lblPhonePrefix)
                        .addGap(8, 8, 8)
                        .addComponent(txtPhone))
                    .addComponent(phoneError, 0, 0, Short.MAX_VALUE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername)
                    .addComponent(usernameError, 0, 0, Short.MAX_VALUE)
                    .addComponent(lblPassword)
                    .addComponent(pwField)
                    .addComponent(pwError, 0, 0, Short.MAX_VALUE)
                    .addComponent(lblConfirmPw)
                    .addComponent(confirmPwField)
                    .addComponent(confirmPwError, 0, 0, Short.MAX_VALUE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBackToLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstName)
                    .addComponent(lblLastName))
                .addGap(4, 4, 4)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fNameError)
                    .addComponent(lNameError))
                .addGap(6, 6, 6)
                .addComponent(lblEmail)
                .addGap(4, 4, 4)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(emailError)
                .addGap(6, 6, 6)
                .addComponent(lblPhone)
                .addGap(4, 4, 4)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhonePrefix)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(phoneError)
                .addGap(6, 6, 6)
                .addComponent(lblUsername)
                .addGap(4, 4, 4)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(usernameError)
                .addGap(6, 6, 6)
                .addComponent(lblPassword)
                .addGap(4, 4, 4)
                .addComponent(pwField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(pwError)
                .addGap(6, 6, 6)
                .addComponent(lblConfirmPw)
                .addGap(4, 4, 4)
                .addComponent(confirmPwField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(confirmPwError)
                .addGap(14, 14, 14)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblBackToLogin)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String fName = txtFName.getText().trim();
        String lName = txtLName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();
        String username = txtUsername.getText().trim();

        String password = new String(pwField.getPassword());
        String confirmPassword = new String(confirmPwField.getPassword());

        // Clearing any previous error message
        clearErrors();

        // Validate individual fields
        boolean valid = true;

        valid = showValidationError(RegisterFieldEnum.FIRST_NAME, fName, fNameError) && valid;
        valid = showValidationError(RegisterFieldEnum.LAST_NAME, lName, lNameError) && valid;
        valid = showValidationError(RegisterFieldEnum.EMAIL, email, emailError) && valid;
        valid = showValidationError(RegisterFieldEnum.PHONE, phone, phoneError) && valid;
        valid = showValidationError(RegisterFieldEnum.USERNAME, username, usernameError) && valid;
        valid = showValidationError(RegisterFieldEnum.PASSWORD, password, pwError) && valid;

        // Validate confirm password
        String confirmError = controller.validateConfirmPassword(password, confirmPassword);

        if (confirmError != null) {
            confirmPwError.setText(confirmError);
            valid = false;
        }

        // Stop execution if invalid prior to database validation
        if (!valid) {
            return;
        }

        // DB Validation
        try {
            if (controller.usernameExists(username)) {
                usernameError.setText("Username already exists");
                valid = false;
            }

            if (controller.emailExists(email)) {
                emailError.setText("Email already exists");
                valid = false;
            }

            if (!valid) {
                return;
            }

            boolean success = controller.petOwnerRegister(fName, lName, email, phone, username, password);

            if (success) {
                JOptionPane.showMessageDialog(null, "Registration Successful");
                dispose();
                new LoginFrame().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Registration Failed", "Registration Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            ErrorHandler.handleSQLException(ex);
        } catch (DatabaseConfigException ex) {
            ErrorHandler.handleDatabaseConfigException(ex);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void confirmPwFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPwFieldActionPerformed
        btnSubmit.doClick();
    }//GEN-LAST:event_confirmPwFieldActionPerformed

    private void lblBackToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackToLoginMouseClicked
        dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_lblBackToLoginMouseClicked

    private void lblBackToLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackToLoginMouseEntered
        lblBackToLogin.setText("<html><u>Back to Login</u></html>");
    }//GEN-LAST:event_lblBackToLoginMouseEntered

    private void lblBackToLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackToLoginMouseExited
        lblBackToLogin.setText("Back to Login");
    }//GEN-LAST:event_lblBackToLoginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new RegisterFrame().setVisible(true);
            } catch (Exception e) {
                logger.log(java.util.logging.Level.SEVERE, null, e);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel confirmPwError;
    private javax.swing.JPasswordField confirmPwField;
    private javax.swing.JLabel emailError;
    private javax.swing.JLabel fNameError;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lNameError;
    private javax.swing.JLabel lblBackToLogin;
    private javax.swing.JLabel lblConfirmPw;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhonePrefix;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel phoneError;
    private javax.swing.JLabel pwError;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel usernameError;
    // End of variables declaration//GEN-END:variables
}
