/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.petcare.view;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 * Shared "Reports" screen for every role. The role panels extend this class
 * and only add their own report cards with {@link #addReport}.
 *
 * @author hirunaka
 */
public class ReportsPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    private static final int CARD_WIDTH = 320;
    private static final int GAP = 15;

    private final List<ReportCard> cards = new ArrayList<>();

    /**
     * Creates new form ReportsPanel
     */
    public ReportsPanel(String subtitle) {
        initComponents();

        lblSubtitle.setText(subtitle);
        cardsPanel.setLayout(new GridBagLayout());

        // Re-flow the cards into more or fewer columns when the window size changes
        addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent e) {
                layoutCards();
            }
        });
    }

    /**
     * Adds a report card; onGenerate runs when its button is clicked.
     */
    protected void addReport(String title, String description, String buttonText, Runnable onGenerate) {
        cards.add(new ReportCard(title, description, buttonText, onGenerate));
        layoutCards();
    }

    private void layoutCards() {

        cardsPanel.removeAll();

        int columns = getWidth() / (CARD_WIDTH + GAP);
        if (columns < 1) {
            columns = 1;
        }
        if (columns > 4) {
            columns = 4;
        }

        GridBagConstraints gbc = new GridBagConstraints();

        gbc.anchor = GridBagConstraints.NORTHWEST;
        gbc.fill = GridBagConstraints.NONE;
        gbc.insets = new Insets(0, 0, GAP, GAP);
        gbc.weightx = 0;
        gbc.weighty = 0;

        for (int i = 0; i < cards.size(); i++) {

            gbc.gridx = i % columns;
            gbc.gridy = i / columns;
            cardsPanel.add(cards.get(i), gbc);
        }

        // FILL REMAINING SPACE

        GridBagConstraints fillerGbc = new GridBagConstraints();

        fillerGbc.gridx = columns;
        fillerGbc.gridy = 0;
        fillerGbc.gridheight = Math.max(1, (cards.size() + columns - 1) / columns);
        fillerGbc.weightx = 1.0;
        fillerGbc.weighty = 1.0;
        fillerGbc.fill = GridBagConstraints.BOTH;

        JPanel filler = new JPanel();
        filler.setOpaque(false);
        cardsPanel.add(filler, fillerGbc);

        cardsPanel.revalidate();
        cardsPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        cardsPanel = new javax.swing.JPanel();

        setOpaque(false);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(33, 37, 41));
        lblTitle.setText("Reports");

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(108, 117, 125));
        lblSubtitle.setText("Generate reports");

        cardsPanel.setOpaque(false);

        javax.swing.GroupLayout cardsPanelLayout = new javax.swing.GroupLayout(cardsPanel);
        cardsPanel.setLayout(cardsPanelLayout);
        cardsPanelLayout.setHorizontalGroup(
            cardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        cardsPanelLayout.setVerticalGroup(
            cardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle)
            .addComponent(lblSubtitle)
            .addComponent(cardsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(4, 4, 4)
                .addComponent(lblSubtitle)
                .addGap(24, 24, 24)
                .addComponent(cardsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardsPanel;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
