/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.petcare.view;

/**
 * One report card (title, description and a generate button). Used by
 * {@link ReportsPanel} for all three roles.
 *
 * @author hirunaka
 */
public class ReportCard extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    private final Runnable onGenerate;

    /**
     * Creates new form ReportCard
     */
    public ReportCard(String title, String description, String buttonText, Runnable onGenerate) {
        this.onGenerate = onGenerate;

        initComponents();

        lblTitle.setText(title);
        txtDescription.setText(description);
        btnGenerate.setText(buttonText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextArea();
        btnGenerate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 226, 230)), javax.swing.BorderFactory.createEmptyBorder(18, 18, 18, 18)));
        setPreferredSize(new java.awt.Dimension(320, 170));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(33, 37, 41));
        lblTitle.setText("Report title");

        txtDescription.setEditable(false);
        txtDescription.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(108, 117, 125));
        txtDescription.setLineWrap(true);
        txtDescription.setText("Report description");
        txtDescription.setWrapStyleWord(true);
        txtDescription.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        txtDescription.setFocusable(false);
        txtDescription.setOpaque(false);

        btnGenerate.setBackground(new java.awt.Color(0, 121, 107));
        btnGenerate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnGenerate.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerate.setText("Generate Report");
        btnGenerate.setBorderPainted(false);
        btnGenerate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerate.setFocusPainted(false);
        btnGenerate.addActionListener(this::btnGenerateActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtDescription, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGenerate)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(6, 6, 6)
                .addComponent(txtDescription, 0, 134, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        onGenerate.run();
    }//GEN-LAST:event_btnGenerateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
