/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.petcare.view.adminFrames;

import java.awt.Color;
import java.time.format.DateTimeFormatter;

import com.petcare.model.Appointment;
import com.petcare.view.UiStyle;

/**
 *
 * @author hirunaka
 */
public class ViewAppointmentDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form ViewAppointmentDialog
     */
    public ViewAppointmentDialog(Appointment appointment) {
        initComponents();

        getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(null);

        String date = appointment.getAppointmentDate().toLocalDateTime().format(DateTimeFormatter.ofPattern("dd MMM yyyy, h:mm a"));

        // Fill in the appointment details
        lblPetValue.setText(valueOrEmpty(appointment.getPetName()));
        lblOwnerValue.setText(valueOrEmpty(appointment.getOwnerName()));
        lblVetValue.setText(valueOrEmpty(appointment.getVetName()));
        lblDateValue.setText(date);
        lblStatusValue.setText(valueOrEmpty(appointment.getStatus()));
        lblStatusValue.setForeground(statusColor(appointment.getStatus()));
        txtReasonValue.setText(valueOrEmpty(appointment.getReason()));
        txtReasonValue.setCaretPosition(0);
    }

    private String valueOrEmpty(String value) {
        return value == null ? "" : value;
    }

    private Color statusColor(String status) {
        if ("Scheduled".equals(status)) {
            return UiStyle.ACCENT;
        } else if ("Cancelled".equals(status)) {
            return UiStyle.ERROR;
        }
        return UiStyle.TEXT_DARK;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPetKey = new javax.swing.JLabel();
        lblPetValue = new javax.swing.JLabel();
        lblOwnerKey = new javax.swing.JLabel();
        lblOwnerValue = new javax.swing.JLabel();
        lblVetKey = new javax.swing.JLabel();
        lblVetValue = new javax.swing.JLabel();
        lblDateKey = new javax.swing.JLabel();
        lblDateValue = new javax.swing.JLabel();
        lblStatusKey = new javax.swing.JLabel();
        lblStatusValue = new javax.swing.JLabel();
        lblReasonKey = new javax.swing.JLabel();
        reasonScrollPane = new javax.swing.JScrollPane();
        txtReasonValue = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();

        setTitle("Appointment Details");
        setModal(true);
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(33, 37, 41));
        lblTitle.setText("Appointment Details");

        lblPetKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPetKey.setForeground(new java.awt.Color(108, 117, 125));
        lblPetKey.setText("Pet");

        lblPetValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPetValue.setForeground(new java.awt.Color(33, 37, 41));
        lblPetValue.setText("Pet name");

        lblOwnerKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblOwnerKey.setForeground(new java.awt.Color(108, 117, 125));
        lblOwnerKey.setText("Owner");

        lblOwnerValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOwnerValue.setForeground(new java.awt.Color(33, 37, 41));
        lblOwnerValue.setText("Owner name");

        lblVetKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblVetKey.setForeground(new java.awt.Color(108, 117, 125));
        lblVetKey.setText("Veterinarian");

        lblVetValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVetValue.setForeground(new java.awt.Color(33, 37, 41));
        lblVetValue.setText("Vet name");

        lblDateKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDateKey.setForeground(new java.awt.Color(108, 117, 125));
        lblDateKey.setText("Date & Time");

        lblDateValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDateValue.setForeground(new java.awt.Color(33, 37, 41));
        lblDateValue.setText("Date and time");

        lblStatusKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblStatusKey.setForeground(new java.awt.Color(108, 117, 125));
        lblStatusKey.setText("Status");

        lblStatusValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatusValue.setForeground(new java.awt.Color(0, 121, 107));
        lblStatusValue.setText("Status");

        lblReasonKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblReasonKey.setForeground(new java.awt.Color(108, 117, 125));
        lblReasonKey.setText("Reason");

        reasonScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)));

        txtReasonValue.setEditable(false);
        txtReasonValue.setColumns(20);
        txtReasonValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtReasonValue.setForeground(new java.awt.Color(33, 37, 41));
        txtReasonValue.setLineWrap(true);
        txtReasonValue.setRows(4);
        txtReasonValue.setWrapStyleWord(true);
        txtReasonValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10));
        reasonScrollPane.setViewportView(txtReasonValue);

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(33, 37, 41));
        btnClose.setText("Close");
        btnClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 212, 218)));
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusPainted(false);
        btnClose.addActionListener(this::btnCloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPetKey, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOwnerKey)
                            .addComponent(lblVetKey)
                            .addComponent(lblDateKey)
                            .addComponent(lblStatusKey)
                            .addComponent(lblReasonKey))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPetValue, 0, 264, Short.MAX_VALUE)
                            .addComponent(lblOwnerValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVetValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDateValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatusValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reasonScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPetKey)
                    .addComponent(lblPetValue))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOwnerKey)
                    .addComponent(lblOwnerValue))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVetKey)
                    .addComponent(lblVetValue))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateKey)
                    .addComponent(lblDateValue))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusKey)
                    .addComponent(lblStatusValue))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReasonKey)
                    .addComponent(reasonScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblDateKey;
    private javax.swing.JLabel lblDateValue;
    private javax.swing.JLabel lblOwnerKey;
    private javax.swing.JLabel lblOwnerValue;
    private javax.swing.JLabel lblPetKey;
    private javax.swing.JLabel lblPetValue;
    private javax.swing.JLabel lblReasonKey;
    private javax.swing.JLabel lblStatusKey;
    private javax.swing.JLabel lblStatusValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVetKey;
    private javax.swing.JLabel lblVetValue;
    private javax.swing.JScrollPane reasonScrollPane;
    private javax.swing.JTextArea txtReasonValue;
    // End of variables declaration//GEN-END:variables
}
